<?php
/**
 * ManiyaTech
 *
 * @author        Milan Maniya
 * @package       ManiyaTech_BuyNow
 */

/**
 * @var \ManiyaTech\BuyNow\Block\Product\ListProduct $block
 * @var \ManiyaTech\BuyNow\ViewModel\BuyNow $viewModel
 */
$viewModel = $block->getViewModel();
if (!$viewModel->isEnabled()) {
    return;
}
$buttonTitle = $viewModel->getButtonTitle();
?>
<div class="maniyatech-buy-now-list"
     data-mage-init='{"ManiyaTech_BuyNow/js/buy-now-list": {}}'>
    <button type="submit"
            title="<?= $escaper->escapeHtml(__($buttonTitle)) ?>"
            class="action primary maniyatech-buynow-btn-list">
        <span><?= $escaper->escapeHtml(__($buttonTitle)) ?></span>
    </button>
</div>
